### ISSUE TITLE
Please update readme - using this will be considered as an cheat

### ISSUE THREAD

**Issue by LesTR** [rocheio/quake-timer#1]
This is something which was in mostly all quakes not allowed to use and reason for ban (except Quake II). Quake champions is not exception. 

Will be at least nice write it into readme. I hope you create this just as learning program and you or other don't use it. Please don't ruin that game, timing was always one of many skills needed for to be good in any quake.

**Comment by rocheio** [comment]
I hear you. This application was really just a for-fun project that I made to share with some friends and see if I could create a useful add-on for a game we were all playing. Practically speaking, it wouldn't be effective for competitive use since the keybinds fall off after a few minutes, and (like your PR suggests) we found it to be more effective to just do the math in our heads and call out when an item would be available (e.g. "heavy at 4:25") over voice chat.

I will update the README to reflect this. However, is this program actually against the rules of public multiplayer on Steam or just in specific tournaments? My thought when creating the app was that since it was completely player-triggered and was not aware of the running game process that it was more of an add-on than a cheat.

**Comment by LesTR** [comment]
Hi, i get it, it's nothing agains official game rules (don't know, probably, sadly, i don't read it) or your code. But all official tournaments have this in own rules.

I play quake from Quake I and all timers was prohibited (ok except Quake II which is special). I hope you write this just for fun and enjoy the game but in this case you can use is too much for me, why don't use "in game" timers - that circles displayed on top of items - they are not available in ranked games but its included in game so what ever. That's the different! What is and what isn't included in games!

You did something else, yes you create add-on (that's right) but where is the difference between add-on and cheat? If you play with this agains someone who doesn't have this, do you have advantage?  Yes, you have! Than is it an cheat. Sorry, thats true.

How you will call aimbot script? Cheat or add-on? It's same, it's still something which give you advantage, do you see my point?

My point was just about not giving advantage by some script, even inform user about possible ban , special when timing is easy as in QC => major items response in 30s. What the fuck?

**Comment by LesTR** [comment]
Still thanks for that readme update.
